#     ____                                __  __  _
#    / __ \___  ____  ____     ________  / /_/ /_(_)___  ____ ______
#   / /_/ / _ \/ __ \/ __ \   / ___/ _ \/ __/ __/ / __ \/ __ `/ ___/
#  / _, _/  __/ /_/ / /_/ /  (__  )  __/ /_/ /_/ / / / / /_/ (__  )
# /_/ |_|\___/ .___/\____/  /____/\___/\__/\__/_/_/ /_/\__, /____/
#           /_/                                       /____/

# This file defines settings of this repository. Most if it is inherited from https://github.com/h3x89/github-settings/blob/master/.github/settings.yml

_extends: h3x89/github-settings:.github/settings.yml

repository:

  name: vs-cursor-sync

  description: Sync VS Code settings with Cursor

  private: false

  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled

  # test 

# branches:
#   - name: main
#     protection:
#       required_pull_request_reviews:
#         required_approving_review_count: 1
#         dismiss_stale_reviews: true
#         require_code_owner_reviews: true
#         dismissal_restrictions:
#           users: []
#           teams: []
#       required_status_checks:
#         strict: true
#         contexts: ["JSON linter"]
#       enforce_admins: false
#       required_linear_history: true
#       restrictions: null
